### ISSUE TITLE
the renegotiation timeout cause problem with long staying connections

### ISSUE THREAD

**Issue by chris968** [mikejonesey/openvpn-2fa#2]
the renegotiation timeout cause problem with long staying connections, when the client try to renegotiate he send the 2nd factor code generated during the initial connection and silently fail, the connection seems up and running but no traffic flowing through it.

**Comment by mikejonesey** [comment]
Yep, bump up the reneg time, perhaps 8hours, common vpn clients don't
support sourcing 2fa tokens and even if they did, this has it's own
implications. Reneg sec is essentially the max time a user can be
authenticated for. Most might set this to 8hours.

Depends on your application and how long you are OK authenticating users
for.

Openvpn have lots of documentation on renegsec.

I have updates to this role, will push them soon.

**Comment by chris968** [comment]
it might be helpful if some openvpn parameters get configurable through variables

**Comment by mikejonesey** [comment]
uploaded some vars for you
